# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          console.log('url', process.env.ACTIONS_ID_TOKEN_REQUEST_URL)
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          console.log('token', id_token)
          coredemo.setOutput('id_token', id_token)
